### ISSUE TITLE
`MS3Record.record` and const

### ISSUE THREAD

**Issue by damb** [EarthScope/libmseed#100]
This is rather a question than an issue.

The `MS3Record` struct has the `record` attribute to store the *raw* miniSEED record buffer the struct was created from (if available). Is there a reason why the attribute is not declared as `const`?, i.e.

```c
struct MS3Record {
  const char* record;
  ...
};
```

Do you see a scenario, where it might be useful to modify the raw miniSEED record buffer?

If declaring the attribute as `const`, as a consequence, the function signature of functions such as e.g. `msr3_parse()` could be changed to

```c
int msr3_parse(const char* record, ...)
```

I hope, I don't miss anything.

**Comment by chad-earthscope** [comment]
Probably just historical oversight.  For the particular case of `MS3Record.record`, the data has already been parsed and the caller can do whatever it wishes with that data without effecting library operations.  _But_ we wouldn't want invite the caller to modify such an internal buffer and risk the caller writing beyond the bounds of the record.

I've created #101 that adds the `const` qualifier to multiple declarations of a record pointer.  I'd appreciate your review if you have time.

**Comment by damb** [comment]
Actually my reasoning was counterintuitive. When calling functions such as `msr3_parse(const char* record, ...)` clients using the function can be sure that the buffer `record` is pointing to won't be modified. With a non-const pointer this isn't the case.
