### ISSUE TITLE
Maximum record length validation when packing header

### ISSUE THREAD

**Issue by damb** [EarthScope/libmseed#111]
This is rather a question than a real issue.

Is there a reason I'm not aware of why `msr3_pack_header3()` validates the maximum record length? In particular, I'm referring to https://github.com/EarthScope/libmseed/blob/b17f7dc8632af430c8f41056d297cf75f6093a58/pack.c#L511-L515.

Similarly, the same question may apply to `msr3_pack_header2()`.

**Comment by chad-earthscope** [comment]
These routines can be run independent from full record packing, to just pack a header.  So they need to independently check if the record length is within allowed limits.

**Comment by damb** [comment]
As a user of the routines I wouldn't have expected this. Neither the routine signature nor the routine documentation gives any hint that *just* packing the header implies checking the configured record length. Instead, as a user I'd expect that as long as the provided buffer is big enough to store the packed header data, packing the header should succeed, i.e. independently of the configured `MS3Record.reclen` attribute. As you stated, a user may run the routines independent from full record packing.

**Comment by chad-earthscope** [comment]
On more review, I belive the intention was to avoid allowing the caller to create headers that the library could not write or read, which seems mostly pointless.

It's also rather small and I cannot think of any case where removing the check would provide reasonable functionality.
