### ISSUE TITLE
leap second file

### ISSUE THREAD

**Issue by crotwell** [EarthScope/libmseed#112]
docs for ms_readleapsecondfile() say to get leap second file from
https://www.ietf.org/timezones/data/leap-seconds.list
but link gives:
`ietf.org is no longer serving this file.`

Related: https://github.com/EarthScope/mseedindex/issues/9

**Comment by chad-earthscope** [comment]
While an external leap second list shouldn't be needed anymore because the list is embedded, the link shouldn't be dead.  I've updated the function docs to include this, presumably stable link:

https://www.rfc-editor.org/rfc/rfc8633.html#section-3.7

**Comment by crotwell** [comment]
sounds good. 
My understanding is that no leap seconds will be added after 2035, but might be some between now and then. Hopefully not, but...

**Comment by crotwell** [comment]
If external leap second list isn't needed, should the warning be removed?
```
Warning: No leap second file specified with LIBMSEED_LEAPSECOND_FILE
  This is highly recommended, see man page for details.
```

**Comment by chad-earthscope** [comment]
Where are you seeing this Warning?

**Comment by crotwell** [comment]
mseedindex, but I think it was the previous version. Can't reproduce now, so ignore.
