### ISSUE TITLE
Maximun number of sampels per record

### ISSUE THREAD

**Issue by Gilaverbuch** [EarthScope/libmseed#113]
Hi, 

I was wondering if there is a limit to the number of samples allowed per record. From trial and error it seems like msr3_writemseed() stops writing proper files when n_samples > 100000.
Am I doing something wrong or is there a limit on the number of samples?

Thanks,
Gil

**Comment by chad-earthscope** [comment]
Hi @Gilaverbuch 
The maximum number of samples allowed per record depends on a number of factors including record length, sample count field value type, use of compression, and of course format version.

I would strongly recommend against creating huge records.  Instead, I'd start with 4k (4096) bytes records if you want high compatibility or perhaps 8k or 16k records if you're willing to risk compatibility.  miniSEED is intended to be a "chunked" format, where records are the chunks.  The current release version of the library is limited to 131,172 bytes, for v3 records, and 131,072 bytes for v2 records (which is 2^17).  How many samples you can pack into these record sizes depends on encoding, i.e. compression type or uncompressed.

**Comment by chad-earthscope** [comment]
Hi @Gilaverbuch ,

That makes a lot of sense.  In v3.0.18 of the library the maximum record length has been increased to 10 megabytes for format version 3 to allow more efficient usage with high rate data.

Of course if you are looking for broad compatibility short term (before v3 is broadly supported) you'll still want to use format version 2 which is limited to 65,535 samples per record, which is the reason for the 131 KiB record length limit.
