### ISSUE TITLE
Massive duplication of data records reduces to least efficient mstl3_ addmsr() search/match

### ISSUE THREAD

**Issue by chad-earthscope** [EarthScope/libmseed#67]
In a test case with a record that has been repeated ad nauseam, e.g. 150,000 times, the search/match algorithm in mstl3_addmsr() (aka mstl3_addmsr_recordptr()) is reduced to
its least efficient, linear search of the record list and reading becomes quite slow.

**Comment by ivor52** [comment]
possible solution: maybe limit overlaps (does this qualify as such?) to some reasonable number, and throw the rest away?

while this is easy to apply to a single, repeating, data packet, maybe not so easy to apply to other weird data instances.  these problems are difficult to generalize to accurately identify 100% of all situations correctly, as you know well.

**Comment by chad-iris** [comment]
Currently, once checking the record-to-be-added against the first, last and all coverage of the already-read segments.

A potential optimization is to search the list from last to first.  Or to do a simple calculation and search _either_ from the first or the last depending on which was closer to the record-to-be-added and use knowledge of the time order of the list (needs to be checked) to end the search once impossible to match.

**Comment by chad-iris** [comment]
> possible solution: maybe limit overlaps (does this qualify as such?) to some reasonable number, and throw the rest away?

Problem is that it takes this logic to know when there are overlaps, and then questions of _is it really_ overlapped (i.e. do the samples actually map)?  That approach involves too many high-level decisions in my opinion for the library.  Better to find an efficient way to do what the caller asked, and stick to if the data is messy the output is messy.

**Comment by ivor52** [comment]
yep, totally agree

**Comment by chad-earthscope** [comment]
Reviewing this logic, the recommended steps:
1. At https://github.com/EarthScope/libmseed/blob/main/tracelist.c#L514, search the existing list from last to first, optimizing for data read in time order.
2. Potentially add test for exact duplicate and place record after the first match, no auto-healing needed

**Comment by chad-earthscope** [comment]
Turns out reversing the search order did not benefit very many test cases, and cases of time-ordered data, gappy or not, are already well handled.

On the other hand, an additional check for duplicate data records when `autoheal` is enabled (should be always), where a record coverage matches a segment in the list, makes a huge difference for duplicated records.
