### ISSUE TITLE
Writing miniSEED file with example script gives file in unknown format

### ISSUE THREAD

**Issue by MarcoEsposito890** [EarthScope/libmseed#87]
Hello,

I'm just starting to use the libmseed library. Following the examples, I generated a miniSEED file using the lm_pack example in the examples folder.

If I parse it using the lm_parse example, I'm able to read the generated miniSEED file. If I try to do the same using Obspy, I get a "Unknown format for file test.mseed" error.

I'm unsure whether that C script is generating a faulty miniSEED file, or not generating a proper miniSEED file at all?

**Comment by chad-earthscope** [comment]
Hi @MarcoEsposito890 ,

I'm guessing you are using the `pre-release` v3.x branch of the library.  This version writes miniSEED, by default, in a draft version of the miniSEED specification.  This would exlain why limbseed v3 programs can read the data, and other tools, e.g. ObsPy, cannot.

If you wish to create the current, SEED v2.4, specification (which is baiscally the only miniSEED in use), your options are:

a. With libmseed v3 add the `MSF_PACKVER2` flags to the `flags` argument of the packing routines.
b. Use libmseed v2: https://github.com/EarthScope/libmseed/releases/tag/v2.19.8
